# Generated by Django 4.1.3 on 2023-05-28 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainNetwork',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='blockchain network')),
                ('chain_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='chain id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='currency')),
                ('symbol_primary', models.CharField(blank=True, max_length=10, null=True, verbose_name='symbol primary')),
                ('symbol_aliases', models.CharField(blank=True, max_length=100, null=True, verbose_name='symbol aliases')),
                ('coingecko_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='coingecko id')),
                ('token_address_on_network', models.CharField(blank=True, max_length=512, null=True, verbose_name='token address on network')),
                ('decimals', models.IntegerField(blank=True, null=True)),
                ('asset_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='Currency Logo')),
                ('blockchain_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='payments.blockchainnetwork')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='currency type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_order_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='User Order Id')),
                ('address_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address From')),
                ('address_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address To')),
                ('order_amount', models.FloatField()),
                ('transaction_hash', models.CharField(blank=True, max_length=512, null=True, verbose_name='Transaction Hash')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentBurner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_order_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='User Order Id')),
                ('address_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address From')),
                ('burner_address_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Burner Address To')),
                ('final_address_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Final Address To')),
                ('order_amount', models.FloatField(blank=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=512, null=True, verbose_name='Transaction Hash')),
                ('initial_block_number', models.CharField(blank=True, max_length=512, null=True, verbose_name='Initial Block Number')),
                ('transaction_block_number', models.CharField(blank=True, max_length=512, null=True, verbose_name='Transaction Block Number')),
                ('transaction_block_hash', models.CharField(blank=True, max_length=512, null=True, verbose_name='Transaction Block Hash')),
                ('blockchain_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_burners', to='payments.blockchainnetwork')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_burners', to='payments.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Payment Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='payment type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurplePayMultisigContract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Purple Pay Multisig Contract Name')),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Purple Pay Multisig Contract Address')),
                ('contract_abi', models.JSONField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_audited', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('blockchain_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purple_pay_multisig_contract_addresses', to='payments.blockchainnetwork')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurplePayFactoryContract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Purple Pay Factory Contract Name')),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Purple Pay Factory Contract Address')),
                ('contract_abi', models.JSONField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_audited', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('blockchain_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purple_pay_factory_contract_addresses', to='payments.blockchainnetwork')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to='payments.payment')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to='payments.paymentstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentBurnerSample',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_order_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='User Order Id')),
                ('address_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address From')),
                ('burner_address_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Burner Address To')),
                ('final_address_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Final Address To')),
                ('order_amount', models.FloatField(blank=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=512, null=True, verbose_name='Transaction Hash')),
                ('initial_block_number', models.CharField(blank=True, max_length=512, null=True, verbose_name='Initial Block Number')),
                ('transaction_block_number', models.CharField(blank=True, max_length=512, null=True, verbose_name='Transaction Block Number')),
                ('transaction_block_hash', models.CharField(blank=True, max_length=512, null=True, verbose_name='Transaction Block Hash')),
                ('blockchain_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_burner_samples', to='payments.blockchainnetwork')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_burner_samples', to='payments.currency')),
                ('payment_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_burner_samples', to='payments.paymentstatus')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_burner_samples', to='payments.paymenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_burner_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentBurnerAddressSample',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('burner_address', models.CharField(blank=True, max_length=512, null=True, verbose_name='burner address')),
                ('order_amount', models.FloatField(blank=True, null=True)),
                ('is_used_for_payment', models.BooleanField(default=False)),
                ('transfer_to_merchant_transaction_hash', models.CharField(blank=True, max_length=512, null=True, verbose_name='Transfer to Merchant Tx Hash')),
                ('burner_contract_deploy_status', models.CharField(blank=True, default='not deploy', max_length=100, null=True, verbose_name='Burner Contract Deploy Status')),
                ('burner_contract_deploy_failure_reason', models.CharField(blank=True, max_length=512, null=True, verbose_name='Deploy Fail Reason')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_burner_sample_addresses', to='payments.currency')),
                ('payment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_burner_address_samples', to='payments.paymentburnersample')),
                ('payment_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_burner_address_samples', to='payments.paymentstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentBurnerAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('burner_address', models.CharField(blank=True, max_length=512, null=True, verbose_name='burner address')),
                ('order_amount', models.FloatField(blank=True, null=True)),
                ('is_used_for_payment', models.BooleanField(default=False)),
                ('transfer_to_merchant_transaction_hash', models.CharField(blank=True, max_length=512, null=True, verbose_name='Transfer to Merchant Tx Hash')),
                ('burner_contract_deploy_status', models.CharField(blank=True, default='not deploy', max_length=100, null=True, verbose_name='Burner Contract Deploy Status')),
                ('burner_contract_deploy_failure_reason', models.CharField(blank=True, max_length=512, null=True, verbose_name='Deploy Fail Reason')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_burner_addresses', to='payments.currency')),
                ('payment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_burner_addresses', to='payments.paymentburner')),
                ('payment_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_burner_addresses', to='payments.paymentstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paymentburner',
            name='payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_burners', to='payments.paymentstatus'),
        ),
        migrations.AddField(
            model_name='paymentburner',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_burners', to='payments.paymenttype'),
        ),
        migrations.AddField(
            model_name='paymentburner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_burners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.paymentstatus'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.paymenttype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='payments.currencytype'),
        ),
    ]
