# Generated by Django 4.1.3 on 2023-07-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentburner",
            name="description",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="paymentburnersample",
            name="description",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Description"
            ),
        ),
    ]
