# Generated by Django 4.1.7 on 2023-08-03 17:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentburner_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainNetworkType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='blockchain network')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blockchainnetwork',
            name='network_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_network', to='payments.blockchainnetworktype'),
        ),
    ]
