# Generated by Django 4.1.7 on 2023-08-04 10:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_blockchainnetworktype_blockchainnetwork_network_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockExplorer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='blockchain name')),
                ('url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RPC',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='RPCUrl Name')),
                ('url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blockchainnetwork',
            name='network',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='blockchain network'),
        ),
        migrations.AlterField(
            model_name='blockchainnetwork',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='blockchain name'),
        ),
        migrations.AlterField(
            model_name='blockchainnetwork',
            name='network_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_networks', to='payments.blockchainnetworktype'),
        ),
        migrations.AlterField(
            model_name='blockchainnetworktype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='network type name'),
        ),
        migrations.AddField(
            model_name='blockchainnetwork',
            name='blockexplorer_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_network_default', to='payments.blockexplorer'),
        ),
        migrations.AddField(
            model_name='blockchainnetwork',
            name='blockexplorer_public',
            field=models.ManyToManyField(blank=True, related_name='blockchain_network_public', to='payments.blockexplorer'),
        ),
        migrations.AddField(
            model_name='blockchainnetwork',
            name='rpc_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_network_default', to='payments.rpc'),
        ),
        migrations.AddField(
            model_name='blockchainnetwork',
            name='rpc_public',
            field=models.ManyToManyField(blank=True, related_name='blockchain_network_public', to='payments.rpc'),
        ),
    ]
