# Generated by Django 4.1.7 on 2023-08-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_blockexplorer_rpc_blockchainnetwork_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainnetwork',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
