# Generated by Django 4.1.7 on 2023-08-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_blockchainnetwork_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentburneraddress',
            name='conversion_rate_in_usd',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='conversion rate in usd'),
        ),
    ]
