PROFILE_DOES_NOT_EXIST = "Profile does not exist for this user id"
GET_PROFILE_SUCCESS = "Successfully fetched profile"
CREATE_PROFILE_FAIL = "Profile could not be created"
UPDATE_PROFILE_FAIL = "Profile could not be updated"
DELETE_PROFILE_SUCCESS = "Profile deleted successfully"
DELETE_PROFILE_FAIL = "Profile could not be deleted"
CREATE_USER_SMART_CONTRACT_WALLET_SUCCESS = "Success: User Smart Contract Wallet created successfully!"
CREATE_USER_SMART_CONTRACT_WALLET_FAIL = "Error: User Smart Contract Wallet could not be created!"
