REGISTER_FAILED_MISSING_EMAIL = "Wait! We're missing your email address. Can't leave without it, can we?"
REGISTER_FAILED_MISSING_PASSWORD = "Your password! It seems to have taken a vacation. We need it here, though."
INVALID_PHONE_NUMBER = "Hmm, this phone number doesn't seem right. Did it gain an extra digit overnight?"
VERIFICATION_EMAIL_BODY = "Hi!\n Please use the link below to verify your email \n"
VERIFICATION_EMAIL_SUBJECT = "Purple Pay: Verify your email and enjoy uninterrupted access!"
INVALID_USER = "Whoops! This user doesn’t exist, just like unicorns (sadly)."
VERIFICATION_SUCCESS = "Congratulations! Your verification was successful! Cue the fireworks! 🎆"
VERIFICATION_ACTIVATION_EXPIRED = "Darn, your verification activation seems to have passed its expiration date. Like old milk. 🥴"
VERIFICATION_INVALID_TOKEN = "This verification token is invalid. Maybe it's past its bed-time?"
USER_REGISTRATION_SUCCESS = "Welcome aboard! You've successfully registered. Let the digital adventures begin!"
USER_REGISTRATION_FAIL = "Oh dear, registration failed. Like trying to fit a square peg in a round hole."
AUTH_SUCCESS = "Bingo! Authentication was a success. You're in!"
AUTH_FAIL = "Bummer! Authentication failed. The digital door remains closed."
AUTH_FAIL_INVALID_CREDENTIALS = "Whoopsie daisy! Your credentials seem to be playing hide-and-seek."
AUTH_FAIL_USER_INACTIVE = "Looks like your account is taking a nap. It's currently inactive."
AUTH_FAIL_EMAIL_NOT_VERIFIED = "Oh, snap! Your email hasn't been verified yet. It's like an unopened gift."
AUTH_FAIL_USER_CREATOR_VERIFICATION_PENDING = "Uh-oh! We're still waiting for your creator verification. Tick-tock, tick-tock! ⏰"
LOGOUT_SUCCESS = "You're successfully logged out!"
LOGOUT_FAIL = "Wait, what? You're trying to logout, but we seem to have lost the exit sign. Let's try again."

APP_SCHEME = ''
AUTH_PROVIDERS = {'facebook': 'facebook', 'google': 'google',
                  'twitter': 'twitter', 'email': 'email',
                  'linkedin': 'linkedin'}
BAD_TOKEN = "Your token's being naughty, I'm afraid. It's not the one we're looking for."
WRONG_AUTH_PROVIDER_MESSAGE = "Whoops! Your authentication provider seems to have taken a wrong turn at Albuquerque."
HTTP = 'http'
HTTPS = 'https'
HOST_LOCAL = "http://localhost:8000/"
HOST_GLOBAL_BACKEND_DEV = "https://dev.legitt.club/"
HOST_GLOBAL_BACKEND_STAGING = "https://sit.legitt.club/"
HOST_GLOBAL_BACKEND_PROD = "https://sit.legitt.club/"
HOST_GLOBAL_FRONTEND_DEV = "https://dev.purplepay.app/"
HOST_GLOBAL_FRONTEND_STAGING = "https://staging.purplepay.app/"
HOST_GLOBAL_FRONTEND_PROD = "https://dashboard.purplepay.app/"
RESET_PASSWORD_PATH = "reset-password/"

UNABLE_TO_RESEND_EMAIL = "Unable to send the email"
EMAIL_SEND_SUCCESSFULLY = "Email Resent Successfully!"

RESET_PASSWORD_MESSAGE = "Your password has been successfully reset."
RESET_PASSWORD_EMAIL_SUBJECT = "Purple Pay: Reset your password!"
NO_USER_REGISTERED_WITH_EMAIL = "Oh dear! This email seems lonely. There's no user registered with it."
RESET_PASSWORD_LINK_SENT_MESSAGE = "Password reset link sent to your email successfully!"
USER_NOT_RECOGNISED = "Whoa there, stranger! We don't seem to recognize this user. New in town?"
INVALID_TOKEN = "That token's playing up, I'm afraid. It's not valid, you see."
VALID_TOKEN_PASSWORD_RESET = "Oh la la! Your token is valid for a password reset. Onward to a fresh start!"
INVALID_RESET_PASSWORD_LINK = "Oopsie daisy! The reset password link is broken. Like a swing with no seat."
RESET_PASSWORD_SUCCESS = "Well done! You've successfully reset your password. You're back in business!"
RESET_PASSWORD_FAIL = "Blast! The password reset didn't work. It's as stubborn as a mule."
RESET_PASSWORD_FAIL_WRONG_AUTH_PROVIDER = "Oh, no! The wrong authentication provider is causing a kerfuffle with your password reset."
INCORRECT_PASSWORD = "Blast! Your password isn't right. Maybe it forgot its lines?"
CHANGE_PASSWORD_SUCCESS = "Way to go! You've successfully changed your password. You'll never guess it now."
CHANGE_PASSWORD_FAIL = "Oh dear! Changing your password failed. Like trying to make a cat bark."
FETCH_USER_DETAILS_SUCCESS = "Aha! We've successfully fetched your user details. They were playing hide-and-seek."
FETCH_USER_DETAILS_FAIL = "Oh no! We tried to fetch your user details, but they're nowhere to be found."
