# Starter pipeline
trigger:
- staging

resources:
- repo: self

jobs:
- job: PurplePay_Dev
  displayName: 'PurplePay sit build'

  pool:
    name: 'purplepay-agent'
  
  variables:
  - group: 'Build Dev Configuration'

  steps:
  - script: chmod +x ./update_version.sh
    displayName: 'Give auto version increment file permission'

  - script: ./update_version.sh
    displayName: 'Update Version'

  - script: echo $(PurplePayNewVersion)
    displayName: 'Print New Version'

  - script: docker login -u $(DOCKER_USER) -p $(DOCKER_PASS) $(DOCKER_REPO)
    displayName: 'docker login'

  - script: docker build -t $(STAGE)/$(IMAGE_NAME):$(PurplePayNewVersion) .
    displayName: 'docker build image'

  - script: docker tag $(STAGE)/$(IMAGE_NAME):$(PurplePayNewVersion) $(DOCKER_REPO)/$(STAGE)/$(IMAGE_NAME):$(IMAGE_TAG)
    displayName: 'docker tag image to latest'

  - script: docker push $(DOCKER_REPO)/$(STAGE)/$(IMAGE_NAME):$(IMAGE_TAG)
    displayName: 'docker latest tag image push into container registry'

  - script: docker tag $(STAGE)/$(IMAGE_NAME):$(PurplePayNewVersion) $(DOCKER_REPO)/$(STAGE)/$(IMAGE_NAME):$(PurplePayNewVersion)
    displayName: 'docker tag image to current version'

  - script: docker push $(DOCKER_REPO)/$(STAGE)/$(IMAGE_NAME):$(PurplePayNewVersion)
    displayName: 'docker current version image push into container registry'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: VERSION'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/VERSION'
      artifactName: drop-build-repo-version