CREATE_KYC_PROFILE_SUCCESS = 'Success: KYC documents uploaded successfully!'
CREATE_KYC_PROFILE_FAIL = 'Error: KYC documents not uploaded!'
GET_KYC_PROFILE_SUCCESS = 'Success: Fetched KYC details submitted successfully!'
GET_KYC_PROFILE_FAIL = 'Error: Could not fetch KYC details submitted!'
UPDATE_KYC_PROFILE_SUCCESS = 'Success: Updated KYC details submitted successfully!'
UPDATE_KYC_PROFILE_FAIL = 'Error: Could not update KYC details submitted!'
DELETE_KYC_PROFILE_SUCCESS = 'Success: KYC documents deleted successfully!'
DELETE_KYC_PROFILE_FAIL = 'Error: Could not delete KYC documents!'
CREATE_POLYGON_ID_SUCCESS = 'Success: Polygon id created successfully!'
CREATE_POLYGON_ID_FAIL = 'Error: Polygon id could not be created!'
API_KEY_INVALID = 'Error: API Key Invalid!'
API_KEY_NOT_FOUND = 'Error: No API Key found for this User Id!'
CREATE_KYC_PROFILE_REQUIRED_SCHEMA_SUCCESS = "Success: Created required schema for KYC Profile!"
CREATE_KYC_PROFILE_REQUIRED_SCHEMA_FAIL = "Error: Could not create required schema for KYC Profile!"
