# Generated by Django 4.1.3 on 2023-05-28 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSmartContractWalletAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_wallet_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='wallet_address')),
                ('user_smart_contract_wallet_address', models.CharField(blank=True, max_length=512, null=True, verbose_name='smart_contract_wallet_address')),
                ('blockchain_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_scw_addresses', to='payments.blockchainnetwork')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_scw_addresses', to='payments.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scw_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_image', models.TextField(blank=True, max_length=300, null=True, verbose_name='profile image')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='middle name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='last name')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='location')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='company')),
                ('agreed_terms_and_conditions', models.BooleanField(default=False)),
                ('agreed_privacy_policy', models.BooleanField(default=False)),
                ('user_wallet_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='wallet_address')),
                ('user_smart_contract_wallet_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='smart_contract_wallet_address')),
                ('company_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='company_url')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='user_profile.usertype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
