# Generated by Django 4.1.7 on 2023-08-04 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_blockexplorer_rpc_blockchainnetwork_network_and_more'),
        ('user_profile', '0002_remove_usersmartcontractwalletaddress_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='payments.blockchainnetwork'),
        ),
    ]
