# Generated by Django 4.1.7 on 2023-08-11 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0003_userprofile_default_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=512, null=True, verbose_name='webhook')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='webhook status')),
                ('secret_key', models.CharField(blank=True, max_length=1024, null=True, verbose_name='secret key')),
                ('event_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='events of interest')),
                ('retry_count', models.IntegerField(default=2)),
                ('payload_format', models.JSONField(blank=True, null=True)),
                ('delivery_response_format', models.JSONField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=32, null=True, verbose_name='version')),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latest_interaction', models.DateTimeField(auto_now=True)),
                ('latest_interaction_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='latest interaction type')),
                ('delivery_response_body', models.CharField(blank=True, max_length=1024, null=True, verbose_name='webhook delivery response')),
                ('delivery_response_status_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='webhook delivery response status')),
                ('error_log', models.TextField(blank=True, null=True)),
                ('webhook_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhookactivity', to='user_profile.webhook')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
