# Generated by Django 4.1.7 on 2023-08-14 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0004_webhook_webhookactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookactivity',
            name='latest_interaction',
        ),
        migrations.AddField(
            model_name='webhookactivity',
            name='requestNonce',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Request Nonce'),
        ),
        migrations.AddField(
            model_name='webhookactivity',
            name='requestPayload',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Request Payload'),
        ),
        migrations.AddField(
            model_name='webhookactivity',
            name='requestSignature',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Request Signature'),
        ),
        migrations.AddField(
            model_name='webhookactivity',
            name='requestTimestampInUnixMs',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Timestamp in Unix ms'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='user_profile.usertype'),
        ),
    ]
