# Generated by Django 4.1.3 on 2023-07-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_keys", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="key_name",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="API Key Name"
            ),
        ),
    ]
