# Generated by Django 4.1.7 on 2023-08-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0003_apikey_key_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='secret_key',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='API Secret Key'),
        ),
    ]
