# Generated by Django 4.1.7 on 2023-08-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0004_apikey_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='api_key_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='API Key Status'),
        ),
    ]
